### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by ghost** [exodus4d/pathfinder_websocket#11]
Hi,

i have limited knowledge in this server setup stuff - especially nginx -  so i have no idea on how to install the websockets properly. I hope someone can point me in the right direction, please.

So far i have a local working pathfinder setup (all green, except websockets) on a virtualbox, network bridged debian stretch server called "debian". I can reach it with http://debian in my network.

- pathfinder is located in /var/www/pathfinder    (pathfinder.conf in /etc/nginx/sites...)
- websocket is located in /var/www/pathfinder_websockets    (i "git cloned it" and executed composer install, adjusted owner and permissions, no errors)

- I can start "php cmd.php" and it seems to be running.

But http://debian/setup can not see it. I guess i am missing some steps.

Is it ok to install the websocket in a new directory in /var/www ?
Do i need another nginx config for the websocket in  /etc/nginx/sites...?
Do i need to add something to the pathfinder.conf in /etc/nginx/sites...?
Both of the last?

Matthl

**Comment by ghost** [comment]
Solved. 
I didn't see the websockets section entries in your pathfinders example nginx.conf and the reverse proxy setup in ../sites-available/pathfinder.conf at first. 
It works now!

**Comment by bradleyshelley** [comment]
How do you set this up
