### ISSUE TITLE
Websocket server using 100% of CPU all the time

### ISSUE THREAD

**Issue by ArtificialQualia** [exodus4d/pathfinder_websocket#4]
I recently configured Websockets for my own Pathfinder instance, and immediately upon starting the websocket server from this project, it uses all the CPU on my AWS server (t2.small) even without any incoming connections.  For everything else on the server (mysql, php-fpm, nginx, etc.) performance has never been an issue as I have a small number of users.

Because of this, Websockets actually perform worse for me than the fallback Ajax method as the server takes longer to respond to requests.

I initially configured websockets for v.1.2.0, but performed the upgrade process all the way to v.1.2.3 to see if that would help, and it has not (this is what I expected, since it is the websocket server that is the problem, and this project has not changed recently).

Here is the rest of the server information from my /setup page:
![image](https://user-images.githubusercontent.com/25773476/27693883-892bcf96-5cb8-11e7-8a98-dd50e7444eba.png)

If you need any other diagnostic information please let me know.

**Comment by Tupsi** [comment]
this is a known issue with the current implementation. You can read up on a lengthy discussion about it in another issue over at the main project. https://github.com/exodus4d/pathfinder/issues/439

Sadly there is no fix yet, so going back to ajax for now is what people do to make it work (again).

**Comment by ArtificialQualia** [comment]
Thanks for the info, I didn't think to check that project for issues with the websocket.

**Comment by exodus4d** [comment]
Should be fixed with 1b9c32f -> https://github.com/exodus4d/pathfinder/issues/439

**Comment by ArtificialQualia** [comment]
Appreciate the heads up!
